## Default meson options ##

# Directories
option('SRC_DIR', type : 'string', value : 'source', description : 'Source directory')
option('SRC_ABOUT', type : 'string', value : 'source/ABOUT', description : 'Source directory containing About information.')
option('SRC_BASE', type : 'string', value : 'source/BASE', description : 'Base directory with 3rd-party binaries to copy into bin_dir')
option('SRC_MWIN', type : 'string', value : 'source/MINWIN', description : 'Source directory for Mini Windows directory')
option('SRC_DOS', type : 'string', value : 'source/DOS', description : 'Source directory for DOS application')
option('BIN_DIR', type : 'string', value : 'bin', description : 'Output directory for built binaries')

# Utilities
option('DOSBOX', type : 'string', value : '', description : 'File path to DOSBOX Application')
option('TCC', type : 'string', value : '', description : 'Folder path to TurboC++')

# MultiPatcher 16BIT DOS Arguments
option('MPC_DOS_ARGS', type : 'string', value : '', description : 'Arguments to pass into MultiPatcher 16-bit DOS application')

# Debug boolean settings
option('QUICK_RUN_16BIT', type : 'boolean', value : false, description : 'Immediately run 16-bit application in DOSBox after TCC compilation')
option('EXIT_ON_16BIT_COMPILATION', type : 'boolean', value : true, description : 'Exit DOSBox after TCC compilation')
option('TCC_OUTPUT_TO_FILE', type : 'boolean', value : true, description : 'Redirect TCC output to a file instead of console')