[MAIN]
name="NVMe driver for Windows NT4/2000"
description="A NVMe (Non-Volatile Memory Express) storage controller driver for Windows 2000, targeting both x86 and Alpha AXP platforms."
author="techomance"
version="1.2.0.0"

[OS]
; not added - don't know how to enable driver installation
;nt4=true
;w2k=true

[NT4]

[W2K]
